format = """
$username$hostname $directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$conda\
$character"""

[username]
show_always = true
style_user = "bold green"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold green"
format = "[@$hostname]($style)"


[directory]
style = "bold cyan"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bold bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "bold cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "bold yellow"

[python]
# symbol = " "
format = "[$virtualenv]($style) "
style = "bold bright-black"
detect_extensions = []
detect_files = []
# symbol = " "
# style = "bold yellow"
# format = "[${symbol}(${virtualenv})]($style) "
# detect_extensions = []
# detect_files = []

[conda]
symbol = " "
style = "bold yellow"
format = "[$symbol$environment]($style) "
ignore_base = true
